---
# tasks file for mysql

- name: install mysql and and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-dev
  sudo: yes
  tags: mysql

- name: Make sure mode 775
  file: path=/var/lib/mysql state=directory mode=0755
  sudo: yes

- name: ensure mysql is running and starts on boot
  sudo: yes
  service: name=mysql state=started enabled=true

- name: create main mysql configuration file
  copy:
    src: my.cnf
    dest: /etc/my.cnf
  notify: restart mysql
  sudo: yes
  tags: mysql

- name: Make sure that the config.d
  file: path=/etc/mysql/conf.d state=directory mode=0755
  sudo: yes

- name: enable mysql
  service:
    name: mysql
    state: started
  sudo: yes
  tags: mysql

- name: install mysqldb python package
  pip:
    name: MySQL-python
    state: present
  sudo: yes
  tags: mysql

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  tags: mysql
  with_items: mysql_hosts

- name: create user level .my.cnf file with root password credentials
  template:
    src: .my.cnf.j2
    dest: "{{ item.home }}/.my.cnf"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0600
  notify: restart mysql
  sudo: yes
  tags: mysql
  with_items: users
