---
# tasks file for nodejs

- name: get currently installed node version
  command: "node --version"
  sudo: yes
  register: result
  ignore_errors: True
  tags: nodejs

#- name: make temp node folder
#  file:
#    path: /tmp/node
#    state: directory
#    mode: 777
#  sudo: yes
#  tags: nodejs

- name: Make sure git is installed
  apt:
    name: git
    update_cache: yes
  sudo: yes
  tags: nodejs

- name: checkout node
  git:
    repo: "git://github.com/ry/node.git"
    dest: "/tmp/node"
    force: no
    accept_hostkey: yes
  tags: nodejs

- name: configure
  sudo: yes
  command: "./configure"
  args:
    chdir: /tmp/node
  when: result.rc !=0
  tags: nodejs

- name: make
  command: "make"
  sudo: yes
  args:
    chdir: /tmp/node
  when: result.rc !=0
  tags: nodejs

- name: make install
  command: "make install"
  sudo: yes
  args:
    chdir: /tmp/node
  when: result.rc !=0
  tags: nodejs

- name: install global nodejs packages
  npm:
    name: "{{ item.name }}"
    state: present
    global: yes
    version: "{{ item.version|default('') }}"
  with_items:
    - {name: 'bower'}
    - {name: 'coffee-script', version: '1.7.1'}
    - {name: 'grunt-cli'}
    - {name: 'less'}
    - {name: 'jshint'}
    - {name: 'coffee-jshint'}
  sudo: yes
  tags: nodejs
